on :
  push:
    braches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'login into dockerhub'
        run: docker login --username habibaeteam --password dckr_pat_ISzOZaFjdWmTQ3QcwF93NfNUR6I 


