on :
  push:
    braches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'testing github actions'
        run: pwd

      - name: 'testing printing'
        run: echo halloworld 


