on :
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'before'
        run: ls

      - uses: actions/checkout@v3
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }} 

      - name: 'Login to DockerHub'
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin


