on :
  push:
    braches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'before'
        run: ls

      - uses: actions/checkout@v3
     
      - name: 'login into dockerhub'
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }} 


